language: haskell

env:
 # - GHCVER=7.8.2
 # - GHCVER=7.8.3
 - GHCVER=7.10.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - cd haddock-library
 - cabal install --only-dependencies --enable-tests
 - cabal install doctest
 - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
 - doctest -isrc -i$(echo vendor/attoparsec-*) -optP-include -optPdist/build/autogen/cabal_macros.h src/Documentation/Haddock/Parser.hs
 - cabal install
 - cd ..
 - (cd haddock-api/ && cabal install --only-dependencies --enable-tests && cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test && cabal install)

script:
 - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
