sudo: true

matrix:
    include:
        - os: linux
          env: MODE="--flavour=quickest"
          addons:
              apt:
                  packages:
                      - ghc-7.10.3
                      - cabal-install-1.22
                      - zlib1g-dev
                  sources: hvr-ghc
          before_install:
              - PATH="/opt/ghc/7.10.3/bin:$PATH"
              - PATH="/opt/cabal/1.22/bin:$PATH"

        - os: osx
          env: MODE="--flavour=quickest --integer-simple"
          before_install:
              - brew update
              - brew install ghc cabal-install
              -

install:
    # Add Cabal to PATH
    - PATH="$HOME/.cabal/bin:$PATH"
    - export PATH
    - env

    # Install all Hadrian and GHC build dependencies
    - cabal update
    - cabal install alex happy ansi-terminal mtl shake quickcheck

    # Fetch GHC sources into ./ghc
    - git clone --recursive git://git.haskell.org/ghc.git --quiet

    # Travis has already cloned Hadrian into ./ and we need to move it
    # to ./ghc/hadrian -- one way to do it is to move the .git directory
    # and perform a hard reset in order to regenerate Hadrian files
    - mkdir ghc/hadrian
    - mv .git ghc/hadrian
    - cd ghc/hadrian
    - git reset --hard HEAD

script:
    # Run internal Hadrian tests
    - ./build.sh selftest

    # Build GHC
    - ./build.sh -j $MODE --verbose --no-progress --progress-colour=never --progress-info=brief --profile=-

    # Test GHC binary
    - cd ..
    - inplace/bin/ghc-stage2 -e 1+2

cache:
    directories:
        - $HOME/.cabal
        - $HOME/.ghc
