version: "{build}"

build:
  verbosity: normal

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

os: Visual Studio 2015
deploy: off

install:
  - cmd: |
      SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"
      bash .appveyor.sh prepare

build_script:
  - bash .appveyor.sh build
  - bash .appveyor.sh test

artifacts:
  - path: C:\projects\ghc\ghc-windows.zip
    name: GHC Windows bindist
    type: zip
